### ISSUE TITLE
Environment variables not passed to webhooks

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#1170]
**Current behavior**
When I define an environment variable for a function in my service definition, that variable is available in `process.env` for inline functions. However, these variables are not passed to webhooks.

**Reproduction**
```yaml
functions:
  hello:
    handler:
      webhook:
        url: http://localhost:4000/hello
    type: resolver
    schema: src/hello.graphql
    environment:
      var1: value
```

**Expected behavior?**
In the original feature request for environment variable support, I proposed adding them to the context of the function. This would work for webhooks. They should be part of the request object.
