### ISSUE TITLE
Separate environment variables per function

### ISSUE THREAD

**Issue by maticzav** [graphcool/prisma#1203]
This feature/bug has already been reported, but the repository went down and it is still the same.

**What feature are you missing?**
The ability to use the same source code file in multiple functions and only change behaviour through environment variables.

**How could this feature look like in detail? Tradeoffs?**
```yaml
# Functions
functions:
  # Algolia
  algoliaSyncDocuments:
    handler:
      code:
        src: functions/algolia/sync.js
        environment:
          ALGOLIA_INDEX: documents
          GRAPHQL_TYPE: Document
    type: subscription
    query: functions/algolia/syncDocuments.graphql
  algoliaSyncRequests:
    handler:
      code:
        src: functions/algolia/sync.js
        environment:
          ALGOLIA_INDEX: requests
          GRAPHQL_TYPE: Request
    type: subscription
    query: functions/algolia/syncRequests.graphql
```

I think there are no trade offs as this can be interpreted as a bug.

---- 

**Current behavior**
The example above currently doesn't work, as one of the functions takes the variables from the other.

**Expected behavior?**
All functions should be standalone units, independent from source code location or sharing.
