### ISSUE TITLE
'No valid session' error when deploying with automate ci

### ISSUE THREAD

**Issue by chinclubi** [graphcool/prisma#1225]
**Current behavior**
- I try to deploy my graphcool project with gitlab-ci
- Here is my simple `.gitlab-ci.yml` file
```
stages:
- build

build: 
  stage: build
  only:
    - master
  script:
    - yarn
    - yarn build
    - graphcool login -T \"${GRAPHCOOL_TOKEN}\"
    - graphcool deploy -t test --force
```
- Push my last commit to `master` branch.
- Finally, I receive this error
![screen shot 2560-11-08 at 8 42 28 pm](https://user-images.githubusercontent.com/5950717/32588440-3cebb636-c541-11e7-8c1a-e253d44cd37a.png)

**Reproduction**
1. create graphcool project with `graphcool init`
2. create a simple `.graphcoolrc`
```
targets:
  dev: shared-ap-northeast-1/{{your-gl-project-id}}
  default: dev
clusters:
  default: shared-ap--1
```
3. create a `.gitlab-ci.yml`
```
image: node:6
before_script:
- npm install -g graphcool
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - graphcool login -T \"${GRAPHCOOL_TOKEN}\"
    - graphcool deploy -t test --force
```
4. set `GRAPHCOOL_TOKEN` variable with your graphcool token >> [gitlab ci docs](https://docs.gitlab.com/ee/ci/variables/#secret-variables)
5. commit&push your code to `master` branch

**Comment by kbrandwijk** [comment]
You shouldn't use `graphcool login`. Instead, you should pass the token to the `graphcool deploy` command directly.

**Comment by chinclubi** [comment]
@kbrandwijk 
According to #626, I have updated `.gitlab-ci.yml` and set the env var `GRAPHCOOL_TARGET`. 
```
image: node:6
before_script:
- npm install -g graphcool
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - graphcool deploy
```
I still got an error:
![image](https://user-images.githubusercontent.com/5950717/32851959-16b1bd6c-ca69-11e7-9804-7f3abfbc3995.png)

**Comment by nguansak** [comment]
I also try build ~/.graphcoolrc file with following script
```
image: node:6
before_script:
- npm install -g graphcool
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - echo \"platformToken: ${GRAPHCOOL_TOKEN}\" > ~/.graphcoolrc
    - graphcool deploy -t test --force
```
but Gitlab CI Lint throw the error
**Status**: syntax is incorrect 
**Error**: jobs:deploy:script config should be a string or an array of strings

BTW, I able to work around by using

```
- cp .graphcoolrc_global ~/.graphcoolrc
```

// .graphcoolrc_global

```
platformToken: >-
 <<YOUR_GRAPHCOOL_TOKEN>>
```

but not practical because you have to put the token into a file
