### ISSUE TITLE
opt:target not working when deploying to default target

### ISSUE THREAD

**Issue by seb-z** [graphcool/prisma#1268]
**Current behavior**

Trying to deploy to the default target triggers errors when `${opt:target}` is used in **graphcool.yml**

Running `graphcool deploy` fails with errors like:

`A valid option to satisfy the declaration 'opt:target' could not be found.`

The workaround for now is to explicitly set the target: `graphcool deploy --target dev`

**Reproduction**

This happens given a **graphcool.yml** similar to this:

```
custom:
  dev:
    AUTH0_DOMAIN: "XXXX"
    AUTH0_API_IDENTIFIER: "XXXX"
  prod:
    AUTH0_DOMAIN: "XXXX"
    AUTH0_API_IDENTIFIER: "XXXX"


types: ./types.graphql


functions: 
  authenticate:
    handler:
      code:
        src: ./src/auth0/auth0Authentication.js
        environment:
          AUTH0_DOMAIN: ${self:custom.${opt:target}.AUTH0_DOMAIN}
          AUTH0_API_IDENTIFIER: ${self:custom.${opt:target}.AUTH0_API_IDENTIFIER}
    type: resolver
    schema: ./src/auth0/auth0Authentication.graphql
```

**Expected behavior?**

I would expect for the default target to be used as the **opt:target** value.
