### ISSUE TITLE
Changing a scalar to a relation field results in None.get

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1274]
**Current behavior**

Changing a scalar field to a relational field results in "None.get" error when deploying. Force deploying shows the same behaviour.

**Reproduction**

* `graphcool init`
* `graphcool deploy`
* change `types.graphql` to the following (note that it was previously `name: String` and now `name: Name @relation(name: "Name")`:

```yml
type User @model {
  id: ID! @isUnique
  name: Name @relation(name: "Name")
  dateOfBirth: DateTime
}

type Name @model {
  id: ID! @isUnique
  name: String
  owner: User @relation(name: "Name")
}
```
* `graphcool deploy` -> "None.get"
* `graphcool deploy --force` -> "None.get"

**Expected behavior?**

* `graphcool deploy` should probably abort
* `graphcool deploy --force` should remove the `name: String` field, and add a new relation `Name` between `User` and `Name` with the fields `name: Name` on `User` and `owner: User` on `Name`.
