### ISSUE TITLE
Model type creation without input parameters results in an 'insufficient permissions' error

### ISSUE THREAD

**Issue by martijnvdbrug** [graphcool/prisma#1511]
## Current behavior
Creating a new model type without input scalar fields always returns 'insufficient permissions' error.

## Reproduction
Create a graphcool service with the following model and permissions:

**graphcool.yml**
```
types: ./types.graphql

permissions:

  # TEST
  - operation: Test.read
    authenticated: false
    query: testExists.graphql

  - operation: Test.create
    authenticated: false
    query: testExists.graphql

  - operation: Test.update
    authenticated: false

  - operation: Test.delete
    authenticated: false

rootTokens:
  - gateway
````

**types.graphql**
```
type Test @model {

    id: ID! @isUnique
    createdAt: DateTime!
    updatedAt: DateTime!

    name: String
}
```

**testExists.graphql**
```
query test {
  SomeTestExists
}
```

**Executing the following query results in 'insufficient permissions':**

```
mutation{
  createTest{
    name
  }
}
```

**Executing this query successfully creates a Test type:**

```
mutation{
  createTest(name:"test"){
    name
  }
}
```

## Expected behavior?
Both queries should result in a model type Test being created.
