### ISSUE TITLE
TypeScript type definitions from application schema

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma#1860]
# Feature Request

**What feature are you missing?**

Having the type definitions based on the `Prisma database schema` is really really nice! Changing those types in the `Application schema` is not a seldom use case. Therefore, having TypeScript type definitions for the changed types would also be super sweet.

This is especially handy if you want to use return types in your resolvers:

```typescript
const myResolver = async (parent, input: MyInput, context: Context, info): Promise<MyChangedUser> => {};
```

**How could this feature look like in detail? Tradeoffs?**

`graphql prepare` could also be responsible of creating the TypeScript type definitions from `src/schema.graphql`.

**Comment by marktani** [comment]
`prisma deploy` runs `graphql prepare` for the `database` project entered in `.graphqlconfig` automatically.

To run `graphql prepare` for the `app` project, you can do

```
graphql prepare -p app -o src/generated --bundle --save
```

If you configure your `app` project in `.graphqlconfig.yml` with the correct generator, you can easily accomplish what you describe.

**Comment by akoenig** [comment]
Ah, I tried that and it didn't work 😳 It turned out that my `.graphqlconfig.yml` was not properly configured 😠 Fixed that, closing here 😀

**Comment by akoenig** [comment]
As always, thanks @marktani :)

**Comment by akoenig** [comment]
@marktani But ... I have imports from /src/generated/prisma.graphq` within my `src/schema.graphql`, with this configuration:

```
  app:
    schemaPath: src/schema.graphql
    extensions:
      prepare-binding:
        output: src/generated/app.ts
        generator: prisma-ts
      endpoints:
        default: 'http://localhost:4000'
```

I get the exception that `Type X not found in document`. Seems to have a problem with imports or do I miss a specific argument / configuration?
