### ISSUE TITLE
Installing a Server-side subscription fails

### ISSUE THREAD

**Issue by akoenig** [graphcool/prisma#1922]
# Bug Report

**Current behavior**

When I define a server-side subscription query in my `prisma.yml` and try to `prisma deploy` it to my `local`, cluster I receive the following response:

```
ERROR: Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cjdq6pu0o001d0143keb01hmj

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cjdq6pu0o001d0143keb01hmj",
      "path": [
        "deploy"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "cluster:cluster:cjdq6pu0o001d0143keb01hmj"
    }
  ],
  "status": 200
}
```

This is from the cluster logs: https://gist.github.com/akoenig/e247bd79748c720007db1390a205f7b1

I'm using `1.3.0-beta.1`

My `prisma.yml`:

```yml
service: my-service

stage: ${env:PRISMA_STAGE}

secret: ${env:PRISMA_SECRET}

datamodel: ...

cluster: ${env:PRISMA_CLUSTER}

subscriptions:
  userChangedFirstName:
    webhook:
      url: https://server-side-subscription.localtunnel.me/
      headers:
        Content-Type: application/json
        Authorization: Bearer foobar
    query: |
      {
        profile(where: {
          mutation_in: [UPDATED]
        }) {
          node {
            firstName
          }
        }
      }

seed:
  import: utils/seed.graphql

```

**Expected behavior?**

The server-side subscription should be deployed 😀
