### ISSUE TITLE
Make TypeScript type definitions from application schema work with Imports from Prisma

### ISSUE THREAD

**Issue by nickluger** [graphcool/prisma#1968]
1. Define your app schema, and use imports from `prisma.graphql` in it:

```graphql
# import DateTime from "./generated/prisma.graphql"

type Foo{
    bar: DateTime
}
```

2. Run 
```shell
yarn graphql prepare -p app --output src/generated -g binding-ts --bindings --bundle --save
```
or just `yarn graphql prepare` if you have a proper definition in your `graphqlconfig.yml`
Mine looks like this
```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      prepare-binding:
        output: src/generated/app.ts
        generator: binding-ts
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts

```

Result:

```
✖ Generating bindings for project app...
Type "DateTime" not found in document.
```
