### ISSUE TITLE
The node-advanced template don't finishes installation

### ISSUE THREAD

**Issue by ellipticaldoor** [graphcool/prisma#1977]
# Bug Report

**Current behavior**
The node-advanced template don't finishes installation

**Reproduction**
``` shell
mkdir test
cd test
prisma init .
# ❯ GraphQL server/fullstack boilerplate (recommended)
# ❯ node-advanced           GraphQL server (incl. database & authentication)
# ❯ local           Local cluster (requires Docker)
```
Afte picking local I get the error
```shell
ERROR: Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cje3dp1gt00030102w3xcd98n

{
  "data": {
    "addProject": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cje3dp1gt00030102w3xcd98n",
      "path": [
        "addProject"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "cluster:cluster:cje3dp1gt00030102w3xcd98n"
    }
  ],
  "status": 200
}
```

**Expected behavior?**
The installation of the template finish and I can start using prisma.

**Comment by marktani** [comment]
how does your `prisma.yml` file look like?

**Comment by ellipticaldoor** [comment]
Like this
```yml
# the name for the service (will be part of the service's HTTP endpoint)
service: test

# the cluster and stage the service is deployed to
stage: ${env:PRISMA_STAGE}

# to disable authentication:
# disableAuth: true
secret: ${env:PRISMA_SECRET}

# the file path pointing to your data model
datamodel: datamodel.graphql

# seed your service with initial data based on seed.graphql
seed:
  import: seed.graphql

cluster: ${env:PRISMA_CLUSTER}
```
