### ISSUE TITLE
Syntax Error GraphQL request Expected Name, found String

### ISSUE THREAD

**Issue by lastmjs** [graphcool/prisma#2033]
I've just installed Prisma and am working with the basic TypeScript backend boilerplate. I'm getting this error when I run prisma deploy. It's stopping the prisma.ts file from being generated:

```
Deploying service `backend` to stage `dev` on cluster `local` 38ms
Service is already up to date.

Hooks:
Checking, if schema file changed 72ms
Writing database schema to `src/generated/prisma.graphql`  1ms
Running $ graphql prepare...
 ▸    Syntax Error GraphQL request (25:3) Expected Name, found String
 ▸    
 ▸    24: type BatchPayload {
 ▸    25:   """
 ▸    ^
 ▸    26:   The number of nodes that have been affected by the Batch operation.
 ▸    
 ▸    
```

Not sure what's going wrong here in the automatically generated prisma.graphql:

```
type BatchPayload {
  """
  The number of nodes that have been affected by the Batch operation.
  """
  count: Long!
}
```

**Comment by marktani** [comment]
What's your `prisma version`?

Your description sounds similar to this discussion: https://github.com/graphcool/prisma/issues/1992
Could you try to apply the resolution described there?

**Comment by lastmjs** [comment]
I was using `1.3.5`, I just tried with `1.4.0-beta.4` and I get the same issue

**Comment by lastmjs** [comment]
I am also already using:

prisma-binding: `1.5.16`
graphql-cli: `2.15.8`

**Comment by lastmjs** [comment]
I just installed a fresh project to try and reproduce, and I can't. I ran a diff on the package-lock.json files, and they are exactly the same. I'm using the same datamodel.graphql files (same contents). Is there some extra state being hidden somewhere that might be causing this to happen?

**Comment by lastmjs** [comment]
datamodel.graphql:

```graphql
type Post {
  id: ID! @unique
  isPublished: Boolean! @default(value: "false")
  title: String!
  text: String!
}

```

prisma.yml:

```yml
# the name for the service (will be part of the service's HTTP endpoint)
service: backend

# the cluster and stage the service is deployed to
stage: dev

# to disable authentication:
# disableAuth: true
secret: mysecret123

# the file path pointing to your data model
datamodel: datamodel.graphql

cluster: local

```
