### ISSUE TITLE
Provided query doesn't include model name - newly deployed service

### ISSUE THREAD

**Issue by delta98** [graphcool/prisma#2064]
# Bug Report

**Current behaviour **

Deploying a new service with a subscription definition results in

```
  Subscription
    ✖ The provided query doesn't include any known model name. Please check for the latest subscriptions API.
```

**Reproduction**

```
service: serviceName
stage: dev
cluster: local
disableAuth: true
datamodel:
  - types.graphql
  - enums.graphql
subscriptions:
  fetchSnippetLexicons:
    query: subscriptions/fetch-snippet-data.graphql
    webhook: ${URL}

```

Removing the subscription and deploying the service, then introducing the subscription into the schema works.

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behaviour?**
