### ISSUE TITLE
prisma playground opens wrong endpoint

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2132]
# Bug Report

**Current behavior**

Running `prisma playground` opens wrong endpoint.

**Reproduction**

```sh
prisma init # choose minimal
prisma deploy
prisma playground
```

This opens `http://localhost:3000/playground` in the browser.

`prisma version`: `prisma/1.4.1 (linux-x64) node-v7.2.0`
`graphql version`: `zsh: command not found: graphql`

`.graphqlconfig.yml`

```yml
projects:
  database:
    extensions:
      prisma: prisma.yml
```

`prisma.yml`

```yml
service: import-id-missing
stage: dev

datamodel: datamodel.graphql

# to enable auth, provide
# secret: my-secret
disableAuth: true
cluster: public-specklemoose-482/prisma-eu1
```

I don't have the Electron App installed.

**Expected behavior?**

It should open `https://eu1.prisma.sh/public-specklemoose-482/import-id-missing/dev`
