### ISSUE TITLE
docker-compose.yml invalid type for upgrade to 1.7

### ISSUE THREAD

**Issue by bialesdaniel** [graphcool/prisma#2255]
# Bug Report

**Current behavior**
 I'm following the new guides for 1.7 and I can't get the docker-compose.yml file right. When I run `docker-compose up -d` I get 
```
ERROR: The Compose file './deployment/docker-compose.yml' is invalid because:
services.prisma.environment.PRISMA_CONFIG contains {"port": 4466, "databases": {"default": {"connector": "mysql", "managementApiSecret": "local-dev-secret", "active": true, "host": "db", "
port": 3306, "user": "root", "password": "prisma"}}}, which is an invalid type, it should be a string, number, or a null
```
https://github.com/graphcool/prisma/issues/new?template=bug.md
**Reproduction**
Run `docker-compose up -d` with the docker-compose.yml example file here: https://www.prisma.io/docs/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b#deprecating-local-commands

**Expected behavior?**
I expect it to create a local docker cluster to deploy to.

**Comment by lucasmafra** [comment]
This is very important issue. I don't think Docker supports object environment variables, I can't see why Prisma documentation suggests a docker-compose file like that.

**Comment by lucasmafra** [comment]
I manage to get it working by adding a pipe in the PRISMA_CONFIG like this:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
            managementApiSecret: my-server-secret-123
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
```
