### ISSUE TITLE
docker-compose.yml Reserved character '@' is not allowed outside quotes

### ISSUE THREAD

**Issue by overpod** [graphcool/prisma#2263]
When you start a local cluster.
I have a mysql user of the form "test @ test"
Cluster 1.7 docker-compose
### Error
``` bash
Exception in thread "main" com.typesafe.config.ConfigException$Parse: String: 7: Expecting close brace } or a comma, got '@' (Reserved character '@' is not allowed outside quotes) (if you intended '@' (Reserved character '@' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
```

**Comment by marktani** [comment]
Can you show your entire `docker-compose.yml` file?

**Comment by overpod** [comment]
```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: abuga.mysql.database.azure.com
            port: 3306
            user: ""trofimov@abuga""
            password: ********
            managementApiSecret: ******
```

**Comment by overpod** [comment]
```bash
docker-compose up
```

**Comment by overpod** [comment]
```yml
            active: true
            host: abuga.mysql.database.azure.com
            port: 3306
            "user: trofimov@abuga"
```
### Error
```bash
prisma_1  | Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: while scanning a simple key
prisma_1  |  in 'string', line 9, column 5:
prisma_1  |         'user: trofimov@abuga'
prisma_1  |         ^
prisma_1  | could not find expected ':'
prisma_1  |  in 'string', line 10, column 5:
prisma_1  |         password: 'ZXcasdqwe123'
prisma_1  |         ^
prisma_1  |
prisma_1  |     at scala.sys.package$.error(package.scala:27)
prisma_1  |     at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:38)
prisma_1  |     at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:38)
prisma_1  |     at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:15)
prisma_1  |     at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:12)
prisma_1  |     at scala.Function0.apply$mcV$sp(Function0.scala:34)
prisma_1  |     at scala.Function0.apply$mcV$sp$(Function0.scala:34)
prisma_1  |     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
prisma_1  |     at scala.App.$anonfun$main$1$adapted(App.scala:76)
prisma_1  |     at scala.collection.immutable.List.foreach(List.scala:389)
prisma_1  |     at scala.App.main(App.scala:76)
prisma_1  |     at scala.App.main$(App.scala:74)
prisma_1  |     at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:12)
prisma_1  |     at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
prisma_prisma_1 exited with code 1
```
