### ISSUE TITLE
PRISMA_MANAGEMENT_API_SECRET not working at 1.7

### ISSUE THREAD

**Issue by lucasmafra** [graphcool/prisma#2266]
I'm trying to use the management api secret to secure my Prisma Server, as it is described in the [documentation](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/docker-aira9zama5). 

**Current behavior**
I can add projects, remove and deploy to my Prisma Server without a token.

**Reproduction**
- I just followed the example described [here](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/docker-aira9zama5)

docker-compose.yml:
```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql  # or `postgres`
            active: true
            host: db
            port: 3306        # or `5432` for `postgres`
            user: root
            password: prisma
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
```

Then run docker-compose up -d, go to the browser, open http://localhost:4466/cluster and send some requests without any token

**Expected behavior?**
To reject requests to the cluster that don't have a valid token
