### ISSUE TITLE
schema download doesn't always works

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2284]
# Bug Report

**Current behavior**

```yml
# .graphqlconfig.yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  db:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4466"
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts

```

```yml
# prisma.yml
endpoint: http://localhost:4466/r-2284/dev
datamodel: datamodel.graphql

hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project db
    - graphql prepare
```

`prisma deploy` results in this output:

```sh
Applying changes 2.1s

Your Prisma GraphQL database endpoint is live:

  HTTP:  http://localhost:4466/r-2284/dev
  WS:    ws://localhost:4466/r-2284/dev


post-deploy:
Running echo "Deployment finished" ✔
"Deployment finished"

Running graphql get-schema --project db ✔

Running graphql prepare !
 ▸    Schema '/Users/marktani/projects/playground/prisma/triaging/r-2284/src/generated/prisma.graphql' not found.
 ▸

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ set -x DEBUG "*"
```

Running `prisma deploy` again results in this output:

```sh
Deploying service `r-2284` to stage `dev` to server `local` 57ms
Service is already up to date.

post-deploy:
Running echo "Deployment finished" ✔
"Deployment finished"

Running graphql get-schema --project db ✔
project db - Schema file was created: src/generated/prisma.graphql

Running graphql prepare ✔
```

**Expected behavior?**

The schema download works for the first time.
