### ISSUE TITLE
How do we get generated files I.e prisma.graphql & prisma.ts - post 1.7

### ISSUE THREAD

**Issue by OGNeutron** [graphcool/prisma#2297]
I haven't found a way to perform the same function which we had pre-1.7, that's one of the main features I really liked.

**Comment by mzygmunt** [comment]
1. Install graphql-cli
```
npm i -g graphql-cli
```
2. Add post-deploy hook to prisma.yml:
```
hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project database
    - graphql prepare
```
3. Now you can execute 
```
prisma deploy
```

This is example .graphqlconfig.yml:
```
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:5000/graphql
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```

**Comment by frankdugan3** [comment]
Also covered in the [upgrade guide](https://www.prisma.io/docs/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b#download-the-prisma-graphql-schema-and-invoking-codegen).

**Comment by OGNeutron** [comment]
Did that, still doesn't want to do it, I'll show mine if you want and it keeps saying 

Syntax Error: Unexpected Name "F"

```
projects:
  main_hub_app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```

```
endpoint: http://localhost:4466
datamodel: database/datamodel.graphql
hooks:
  post-deploy:
    # - echo "Deployment finished"
    - graphql get-schema --project prisma
    - graphql prepare
```
