### ISSUE TITLE
[1.7.3] The provided query doesn't include any known model name

### ISSUE THREAD

**Issue by everdrone** [graphcool/prisma#2317]
# Bug Report

**Current behavior**
`prisma deploy` in a new fresh service results in
```
Subscription
  ✖ The provided query doesn't include any known model name. Please check for the latest subscriptions API.
```
**Reproduction**
```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7.3
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
```
```yaml
subscriptions:
  userChangedEmail:
    webhook:
      url: http://email-ses:4200/send
      headers:
        Content-Type: application/json
        Authorization: Bearer foo
    query: |
      subscription {
        user {
          node {
            id
            firstName
            tokenExpires
            email
          }
        }
      }
```
Adding the subscriptions to `prisma.yml` later and deploying again works by the way.

Yes, this is a duplicate of https://github.com/graphcool/prisma/issues/2064, although still occurs in `v1.7.3`, so i guess this deserves some more attention.

**Expected behavior?**
service with server side subscription should deploy without problems
