### ISSUE TITLE
rename Prisma database configuration value `active` to `migrations`

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#2344]
The Prisma server configuration looks like this:

```yml
port: 4466
databases:
  default:
    connector: postgres
    active: true
    host: db
    port: 5432 
    user: prisma
    password: prisma
```

The `active` configuration value decides if Prisma should migrate the underlying database when a new data model is deployed, or simply use the data model to map to the database as is.

User testing has shown that the active/passive distinction is confusing. Instead we will change it to a setting that enables / disables migrations:

```yml
port: 4466
databases:
  default:
    connector: postgres
    migrations: true
    host: db
    port: 5432 
    user: prisma
    password: prisma
```

If the `migrations` field is not present we should default to `true`
