### ISSUE TITLE
server configuration: `migrations` should default to true

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#2366]
These configurations should be equivalent:

```yml
port: 4466
managementApiSecret: somesecret
databases:
  default:
    connector: mysql
    host: localhost
    port: 3306
    user: root
    password: prisma
```

```yml
port: 4466
managementApiSecret: somesecret
databases:
  default:
    connector: mysql
    migrations: true
    host: localhost
    port: 3306
    user: root
    password: prisma
```
