### ISSUE TITLE
CLI: Use volume for databases in generated docker-compose

### ISSUE THREAD

**Issue by sorenbs** [graphcool/prisma#2375]
- [x] rename `db` to `postgres` or `mysql` depending on the chosen database
- [x] add volume to the database
- [x] move migrations to the bottom

Currently we generate the following docker-compose file:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8-beta
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            migrations: true
            host: db
            port: 5432
            user: prisma
            password: prisma
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
```

Instead we should generate the following:

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8-beta
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
```
