### ISSUE TITLE
Serverless framework integration

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#691]
There are two ways to integrate with the [Serverless framework](https://github.com/serverless/serverless):

1) Reference Serverless functions/resources from `graphcool.yml`
2) Reference a Graphcool backend from `serverless.yml`

### Goal

Use the Serverless framework to deploy functions on AWS (or other providers) and reference the deployed functions in the `graphcool.yml` file.

### Design decisions

* Graphcool assumes that during deploy-time all serverless functions are already deployed and can be referenced directly as AWS Lambda function

### Implementation

_TBD_

### Challenges

* Avoid code duplication when referencing a `serverless.yml` file
* IAM permissions (role statements)
* Zero-downtime deployment (blue-green)

### Initial limitations

* Supports only AWS Lambda (other service providers can be added later)

### External todos

- [ ] Serverless needs to provide information about deployed functions/resources in a readable format (e.g. JSON)

## 2) Reference a Graphcool backend from `serverless.yml`

_TBD_

**Comment by kbrandwijk** [comment]
Initial thoughts:
- Having two different configuration files for two different parts of the same solution is really not optimal
- For 'basic' uses (inline functions and existing webhooks) the graphcool.yml method is easiest

- For advanced uses (especially now the CLI has been completely refactored this should be easy), think about exposing the CLI functionality as serverless plugin, and define the entire deployment in the serverless.yml.
- If you go that route, you are not limited to AWS Lambda, expecially now Serverless has just released their plugin for Webtask supporting Node 8!

**Comment by kbrandwijk** [comment]
I'll address a few different topics in different comments.

## Deploying fuctions using serverless to Graphcool or other provider

With serverless, the provider determines where your functions will be deployed. So for deploying functions to Graphcool (as inline functions), Graphcool needs to be defined as provider. For deploying your functions to another provider, Graphcool can be defined as a plugin. For example:

```yaml
# serverless.yml with webtasks provider

service: myProject

provider:
  name: webtasks

functions:
  hello:
    handler: hello
    type: resolver
  after-post-create:
    handler: after-post-create
    type: operationAfter
    operation: Post.create

custom:
  graphcool:
    permissions:
    - operation: Post.create
      authenticated: true

plugins:
  - '@webtask/serverless-webtasks'
  - 'graphcool-webtasks'
```

```yaml
# serverless.yml with aws provider

service: myProject

provider:
  name: aws

functions:
  hello:
    handler: handlers.hello
    events:
    - http:
        path: hello
        method: get
        type: resolver

custom:
  graphcool:
    permissions:
    - operation: Post.create
      authenticated: true

plugins:
  - 'graphcool-aws'
```

```yaml
# serverless.yml with Graphcool provider

service: myProject

provider:
  name: graphcool

functions:
  hello:
    handler: hello
    type: resolver

custom:
  graphcool:
    permissions:
    - operation: Post.create
      authenticated: true
```

**Comment by kbrandwijk** [comment]
## Mix-n-match

There might be scenario's, where you want to combine different services together, deployed to different providers:

```yaml
# service1/serverless.yml

service: service1

provider:
  name: webtasks

functions:
  hello:
    handler: hello
  after-post-create:
    handler: after-post-create

plugins:
  - '@webtask/serverless-webtasks'

# service2/serverless.yml

service: service2

provider:
  name: aws

functions:
  create-post:
    handler: handlers.createPost
    events:
    - http:
        path: create-post
        method: post

# serverless.yml

service: myProject

provider:
  name: graphcool

functions:
  hello:
    webhook: `${self:custom.webtaskBaseUrl}/hello`
    - events:
       - graphcool:
           type: resolver
  create-post:
    webhook: `${self:custom.webtaskBaseUrl}/post-create`
    - events:
       - graphcool:
           type: operationAfter
           operation: Post.create

custom:
  webtaskBaseUrl: 'https://sandbox.it-auth0.com/container'
  awsBaseUrl: 'https://..........'
  graphcool:
    permissions:
    - operation: Post.create
      authenticated: true
```
