### ISSUE TITLE
Wildcard permission not working as expected

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/prisma#722]
I have the following permission setup:

```yaml
permissions:
- operation: "*"
  authenticated: true
```

I expected this to enable authentication on all permissions, but apparently it doesn't
