### ISSUE TITLE
Improve yaml validation for functions

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#934]
![pasted image at 2017_10_19 06_15 pm](https://user-images.githubusercontent.com/1780597/31813365-57c04dfc-b586-11e7-8a4a-1525f08137e6.png)

```yml
functions:
  onResponse:
    handler:
      type: subscription
      code: src/onRequest/index.ts
      query: src/onRequest/query.graphql
```
